name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Kaggle CLI
      run: pip install kaggle

    - name: Setup Kaggle API key
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        mkdir -p $HOME/.kaggle
        echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > $HOME/.kaggle/kaggle.json
        chmod 600 $HOME/.kaggle/kaggle.json

    - name: Download chest x-ray data
      run: |
        kaggle datasets download -d paultimothymooney/chest-xray-pneumonia
        unzip chest-xray-pneumonia.zip -d chest_xray

    - name: Run main program
      run: python train.py

    
    - name: Download dataset
      run: python download_dataset.py
